config/routes.rb
Rails.application.routes.draw do
  root "auctions#index"

  resources :auctions do
    resources :reservings, only: [:create]
    resources :bids, only: [:create]
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :bids, only: [:index]

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  has_many :bids, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :ends_on, presence: true

  include AASM

  aasm whiny_transitions: false do
    state :published, initial: true
    state :reserved_met
    state :won
    state :cancelled
    state :reserved_not_met

    event :reserve do
      transitions from: :published, to: :reserved_met
    end

  end

  def self.get_winning_user(user_id)
    find(user_id)
  end

end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :set_auction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:new, :create, :edit, :update, :destroy]

  # GET /auctions
  # GET /auctions.json
  def index
    @auctions = Auction.order(created_at: :desc)
  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
    @bids = @auction.bids.order(created_at: :desc)
    @bid = Bid.new
  end

  # GET /auctions/new
  def new
    @auction = Auction.new
  end

  # GET /auctions/1/edit
  def edit
    redirect_to auction_path(@auction), alert: "Access denied." and return unless can? :edit, @auction
  end

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new(auction_params)

    @auction.user = current_user

    @auction.current_price = 0;
    @auction.winning_price = 0;

    respond_to do |format|
      if @auction.save
        format.html { redirect_to @auction, notice: 'Auction was successfully created.' }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auctions/1
  # PATCH/PUT /auctions/1.json
  def update
    redirect_to auction_path(@auction), alert: "Access denied." and return unless can? :update, @auction
    respond_to do |format|
      if @auction.update(auction_params)
        format.html { redirect_to @auction, notice: 'Auction was successfully updated.' }
        format.json { render :show, status: :ok, location: @auction }
      else
        format.html { render :edit }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    redirect_to auctions_path(@auction), alert: "Access denied." and return unless can? :destroy, @auction

    @auction.destroy
    respond_to do |format|
      format.html { redirect_to auctions_url, notice: 'Auction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auction_params
      params.require(:auction).permit(:title, :details, :ends_on, :reserve_price)
    end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
  def label_class(state)
    case state
    when "published"
      "label-default"
    when "reserved_met"
      "label-primary"
    when "won"
      "label-success"
    when "cancelled"
      "label-danger"
    when "reserved_not_met"
      "label-warning"
    end
  end
end

app/views/auctions/_form.html.erb
<%= simple_form_for(@auction) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :details %>
    <%= f.input :ends_on %>
    <%= f.input :reserve_price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/auctions/edit.html.erb
<h1>Editing Auction</h1>

<%= render 'form' %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

app/views/auctions/index.html.erb
<h1 class="page-header">Listing Auctions</h1>
<%= link_to 'New Auction', new_auction_path %>
<div>
  <% @auctions.each do |p| %>
    <div class="well clickable_html">
        <%= p.title %>
        <%= link_to "Show", auction_path(p), class: "btn btn-primary btn-sm pull-right", style: "display: none" %>
        <% if can? :manage, p %>
          <%= link_to "Edit", edit_auction_path(p), class: "btn btn-primary btn-sm pull-right"%>
          <%= link_to "Destroy", p, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm pull-right" %>
          <div class="pull-right owned">Owned </div>
        <% end %>

    </div>
  <% end %>
</div>

app/views/auctions/new.html.erb
<h1>New Auction</h1>

<%= render 'form' %>

<%= link_to 'Back', auctions_path %>

app/views/auctions/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @auction.title %>
</p>

<p>
  <strong>Details:</strong>
  <%= @auction.details %>
</p>

<p>
  <strong>Ends on:</strong>
  <%= @auction.ends_on %>
</p>

<% if @auction.reserve_price && current_user == @auction.user%>
<p>
  <strong>Reserve price:</strong>
  $<%= '%.2f' % @auction.reserve_price %>
</p>
<% end %>

<% if @auction.current_price %>
<p>
  <strong>Current price:</strong>
  $<span id="current_price"><%= '%.2f' % @auction.current_price %></span>
</p>
<% end %>

<% if @auction.winning_price && current_user == @auction.user%>
<p>
  <strong>Winning price:</strong>
  $<span id="winning_price"><%= '%.2f' % @auction.winning_price %></span>
</p>
<% if @auction.winning_user %>
  <p>
    <strong>Winning user:</strong>
    <span> <%= get_winning_user(@auction.winning_user).full_name %></span>
  </p>
<% end %>
<% end %>


<p>Created by: <%= @auction.user.first_name %> <%= @auction.user.last_name %></p>

<p><span class="label <%= label_class(@auction.aasm_state) %>"><%= @auction.aasm_state.capitalize %></span></p>


<% if @auction.may_reserve? %>
  <%= link_to "Reserve", auction_reservings_path(@auction),
              method: :post,
              data:   {confirm: "Are you sure you want to set to reserved met?"},
              class:  "btn btn-primary" %>
<% end %>


<%= link_to 'Edit', edit_auction_path(@auction) %> |
<%= link_to 'Back', auctions_path %>

<% if current_user != @auction.user %>
  <h2 id="add_bid_heading">Add a Bid</h2>
  <%= render "/bids/form" %>
<% end %>
<h2>Bids</h2>
<div id="bids">
  <% @bids.each do |bid| %>
    <%= render "/bids/bid", bid: bid %>
  <% end %>
</div>